<?php ob_start(); ?>
    <div class="row mx-2">

        <div class="d-none d-md-block col-md-3 border" id="filtre">
          <div>
            <button class="w-100 mt-2" name="btn">Budget</button>
          </div>
          <div>
            <button class="w-100 mt-2">Ville</button>
          </div>
          <div>
            <button class="w-100 mt-2">Etoiles</button>
          </div>
        </div>

        <div class="col-md-9">
          <div class="row">

            <?php foreach ($chambres as $key => $value): ?>
              <div class="col-12 col-sm-6 col-md-4 d-flex flex-column">
                <img src="image/<?= $value['image'] ?>"  alt="photo">
                <div class="text-center">
                  <a href="?action=detail&idChambre=<?= $value['numChambre'] ?>" class="  btn btn-primary mt-1">
                    Détail
                  </a>
                  <?php if(isset($_SESSION['personnel'])): ?>
                    <?php if($_SESSION['personnel']['role'] == "admin"): ?>
                      <a href="index.php?action=delete&idChambre=<?= $value['numChambre'] ?>&imgChambre=<?= $value['image'] ?>" class="btn btn-danger mt-1">
                      Delete
                      </a>
                      <a href="index.php?action=update&idChambre=<?= $value['numChambre'] ?>" class="btn btn-primary mt-1">
                      Update
                    </a>
                    <?php endif; ?>
                  <?php endif; ?>
                </div>
              </div>
            <?php endforeach; ?>

          </div>
        </div>
    </div>

<?php $content = ob_get_clean();

include 'template.phtml';
