<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="css/style.css">
  <title>Hôtellerie</title>
</head>
<body>
  <header class="bg-secondary p-3 text-center mb-5">
    <div class="text-right"><i class="fa fa-power-off"></i></div>
    <a href="index.php"><h1>Bienvenue sur notre site</h1></a>
    <nav class="navbar navbar-dark">
      <!-- on teste si la session existe -->
     <?php if(isset($_SESSION['personnel'])): ?>
        <a class="text-white" href="index.php?action=deconnexion">Se déconnecter </a>
       <!-- ADMIN & RECEPTIONNISTE -->
        <?php if($_SESSION['personnel']['role'] == "receptionniste" || $_SESSION['personnel']['role'] == "admin"): ?>
          <a class="text-white" href="">Toutes les réservations </a>
        <?php endif; ?>

        <?php if($_SESSION['personnel']['role'] == "admin" ) : ?>
          <!-- ADMIN -->
          <a class="text-white" href="index.php?action=ajouter">Ajouter </a>
        <?php endif; ?>

      <?php else: ?>
        <a class="text-white" href="index.php?action=connexion">Se connecter </a>
    <?php endif; ?>

    </nav>
  </header>
  <main class="container-fluid">

    <?=  $_SESSION['message'] ?? "" ?>

    <?= $content; ?>
  </main>
  <footer class="bg-secondary p-3 text-center mt-3">
    &copy; - Hôtellerie - ILCI
  </footer>
  <?php unset($_SESSION['message']); ?>

  <script src="js/validation.js"></script>
  <script src="js/filtre.js"></script>
</body>
</html>
